import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/utils/utils";
// import { syne } from "@/fonts/font";
import QueryProvider from "@/components/QueryProvider";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/ThemeProvider";
import NextTopLoader from "nextjs-toploader";
import { Toaster as SonnerToaster } from "@/components/ui/sonner";
import GlobalContext from "@/contexts/GlobalContext";

export const metadata: Metadata = {
	title: " Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = "";

	return (
		<html lang="en">
			<body className={cn("antialiased")}>
				{/* <body className={cn("antialiased", syne.className)}> */}
				<NextTopLoader
					showSpinner={true}
					color="#027E02"
					initialPosition={0.05}
					crawlSpeed={350}
					height={2}
					crawl={true}
					easing="ease"
					speed={400}
					shadow="0 0 10px #027E02,0 0 5px #027E02"
				/>
				<QueryProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<GlobalContext>{children}</GlobalContext>
					</ThemeProvider>
					<Toaster />
					<SonnerToaster position="bottom-left" />
				</QueryProvider>
			</body>
		</html>
	);
}
